### PR TITLE
Add tinyhttp

### PR DESCRIPTION
**Pull request by v1rtl**
Hello ✋ 

I'm a creator of [tinyhttp](https://github.com/talentlessguy/tinyhttp)

I'd like to add my framework because it grows quite fast in popularity (I made 126 stars in one week)

### CODE REVIEW

**Comment by v1rtl** [comment]
why is it closed?

**Comment by vanodevium** [comment]
@talentlessguy 
It is because this repo automated by schedule runner, so it closes requests automatically. 
Sorry for this.
I'll add your framework. Good work! Thanks

**Comment by v1rtl** [comment]
@webdevium oh, ok

**Comment by vanodevium** [comment]
@talentlessguy Done. Good luck!

**Comment by v1rtl** [comment]
@webdevium, thx :3

**Pull request closed without merging**
